# Generated by Django 5.2.6 on 2026-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_kyc_property_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('tenant', 'Tenant/User'), ('landlord', 'Owner/Landlord')], default='tenant', max_length=10),
        ),
    ]
