# Generated by Django 5.2.6 on 2026-03-22 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='area_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnishing',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lease_period',
        ),
        migrations.RemoveField(
            model_name='property',
            name='maintenance_fee',
        ),
        migrations.RemoveField(
            model_name='property',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='province',
        ),
        migrations.RemoveField(
            model_name='property',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_floors',
        ),
        migrations.AddField(
            model_name='kyc',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('tenant', 'Tenant/User'), ('owner', 'Owner/Landlord')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('house', 'House')], max_length=20),
        ),
    ]
