# Generated by Django 5.2 on 2026-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('booked', 'Booked'), ('archived', 'Archived')], default='published', max_length=20),
        ),
    ]
