# Generated by Django 5.2 on 2026-05-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_moderationaction_suspension_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('refund_processed', 'Refund Processed'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('admin_action', 'Admin Action')], max_length=50),
        ),
    ]
