# Generated by Django 5.2 on 2026-05-31 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('refund_processed', 'Refund Processed'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('admin_action', 'Admin Action'), ('agreement_created', 'Agreement Created'), ('agreement_tenant_signed', 'Agreement Signed by Tenant'), ('agreement_landlord_signed', 'Agreement Signed by Landlord'), ('agreement_activated', 'Agreement Activated'), ('agreement_expiring', 'Agreement Expiring Soon')], max_length=50),
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_tenant', 'Pending Tenant Signature'), ('pending_landlord', 'Pending Landlord Signature'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending_tenant', max_length=30)),
                ('agreement_content', models.TextField(help_text='Full legal terms and conditions')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_duration_months', models.IntegerField(default=12)),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_email', models.EmailField(max_length=254)),
                ('tenant_phone', models.CharField(blank=True, default='', max_length=20)),
                ('tenant_citizenship', models.CharField(blank=True, default='', max_length=100)),
                ('landlord_name', models.CharField(max_length=255)),
                ('landlord_email', models.EmailField(max_length=254)),
                ('landlord_phone', models.CharField(blank=True, default='', max_length=20)),
                ('landlord_kyc_verified', models.BooleanField(default=False)),
                ('property_name', models.CharField(max_length=255)),
                ('property_address', models.TextField()),
                ('property_type', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant_signature', models.TextField(blank=True, help_text='Base64 encoded signature image', null=True)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('tenant_device_info', models.TextField(blank=True, default='')),
                ('landlord_signature', models.TextField(blank=True, help_text='Base64 encoded signature image', null=True)),
                ('landlord_signed_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('landlord_device_info', models.TextField(blank=True, default='')),
                ('agreement_pdf', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='users.booking')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_agreements', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='users.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
